services:
  - type: web
    name: tradingbot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
    plan: free
