services:
  - type: web
    name: tradingbot
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHONUNBUFFERED
        value: "true"
