services:
  - type: web
    name: tradingbot
    env: python
    buildCommand: chmod +x start.sh && pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    plan: free
