services:
  - type: web
    name: tradingbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
