services:
  - type: web
    name: tradingbot
    env: python
    buildCommand: chmod +x run.sh
    startCommand: ./run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8501
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: false
